[build-system]
requires = ["setuptools>=68.0", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lucidwm"
version = "0.1.0"
description = "Clean single-file implementations of world model algorithms"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10"
authors = [
    {name = "Shaswat", email = "shaswat@lucidwm.dev"},
]
keywords = ["world-models", "model-based-reinforcement-learning", "dreamer", "muzero", "mbrl"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

dependencies = [
    "torch>=2.1.0",
    "numpy>=1.24.0",
    "gymnasium>=0.29.0",
    "shimmy[dm-control]>=1.0.0",
    "dm-control>=1.0.14",
    "tyro>=0.7.0",
    "tensorboard>=2.14.0",
    "tqdm>=4.66.0",
    "opencv-python>=4.8.0",
    "imageio>=2.31.0",
    "cma",
    "swig",
    "gymnasium[box2d]",
    "decord",
    "huggingface_hub",
    "zstandard",
    "hdf5plugin"
]

[project.optional-dependencies]
atari = [
    "ale-py>=0.8.1",
    "gymnasium[atari,accept-rom-license]>=0.29.0",
    "autorom[accept-rom-license]>=0.6.1",
]
crafter = [
    "crafter>=1.8.0",
]
metaworld = [
    "metaworld>=2.0.0",
]
minari = [
    "minari",
]
wandb = [
    "wandb>=0.16.0",
]
all = [
    "lucidwm[atari,crafter,metaworld,wandb, minari]",
]
dev = [
    "ruff>=0.3.0",
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
]

[project.urls]
Homepage = "https://github.com/lucidwm/lucidwm"
Documentation = "https://lucidwm.dev"
Repository = "https://github.com/lucidwm/lucidwm"
Issues = "https://github.com/lucidwm/lucidwm/issues"

[tool.setuptools.packages.find]
include = ["lucidwm*"]

[tool.ruff]
target-version = "py310"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "W", "UP"]

[tool.pytest.ini_options]
testpaths = ["tests"]
